name: 🛡️ OpenSSF Scorecard (Audit)

on:
  # Run on branch protection changes
  branch_protection_rule:
  # Run weekly (to keep results fresh)
  schedule:
    - cron: '20 7 * * 1'
  # Run on push to main branch
  push:
    branches: [ "0.4.1" ]

permissions:
  contents: read
  checks: write

jobs:
  analysis:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to Security tab
      security-events: write
      # Needed to publish results (for badge)
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          # Public repositories:
          publish_results: true

      # (Optional) Save results as artifact for download
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload results to GitHub Security Dashboard
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif